name: 'Cypress evaluator'
description: 'Cypress evaluator action for Tryber projects'
inputs:
  repository-test-name:
    description: 'GitHub repository that store the tests'
    required: true
  repository-test-branch:
    description: 'GitHub specific branch'
    default: 'master'
    required: false
  npm-start:
    description: 'Run npm start and waits to http://localhost:3000 before testing'
    default: true
outputs:
  result:
    description: 'Cypress unit tests JSON results in base64 format.'
  pr-number:
    description: 'Pull Request number that trigger build.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository-test-name }}
    - ${{ inputs.repository-test-branch }}
    - ${{ inputs.npm-start }}
