name: "Cypress evaluator"
description: "Cypress evaluator action for Tryber projects"
inputs:
  npm-start:
    description: "Run npm start and waits to http://localhost:3000 before testing"
    default: false
  headless:
    description: "Hide the browser instead of running headed at Cypress running"
    default: true
  browser:
    description: "Define what browser Cypress must run"
    default: "chrome"
  pr_author_username:
    description: "Pull Request author username"
    required: true
  json-server:
    description: "Initiate json-server start script before testing"
    default: false
  json-server-port:
    description: "Define json-server port"
    default: "3050"
  json-server-db:
    description: "Define json-server db file"
    default: "./server/db.json"
  json-server-routes:
    description: "Define json-server route file"
    default: "./server/routes.json"

outputs:
  result:
    description: "Cypress unit tests JSON results in base64 format."
runs:
  using: "docker"
  image: "docker://betrybe/cypress-evaluator-action:v10.0"
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.headless }}
    - ${{ inputs.browser }}
    - ${{ inputs.json-server }}
    - ${{ inputs.json-server-port }}
    - ${{ inputs.json-server-db }}
    - ${{ inputs.json-server-routes }}
