name: 'Cypress evaluator'
description: 'Cypress evaluator action for Tryber projects'
outputs:
  result:
    description: 'Cypress unit tests JSON results in base64 format.'
  pr-number:
    description: 'Pull Request number that trigger build.'
runs:
  using: 'docker'
  image: 'Dockerfile'
