name: 'Cypress evaluator'
description: 'Cypress evaluator action for Tryber projects'
inputs:
  npm-start:
    description: 'Run npm start and waits to http://localhost:3000 before testing'
    default: false
  headless:
    description: 'Hide the browser instead of running headed at Cypress running'
    default: true
  browser:
    description: 'Define what browser Cypress must run'
    default: 'chrome'
  pr_author_username:
    description: 'Pull Request author username'
    required: true
outputs:
  result:
    description: 'Cypress unit tests JSON results in base64 format.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.headless }}
    - ${{ inputs.browser }}
